# Generated by Django 4.2.11 on 2024-04-08 07:52

from django.db import migrations, models
import django_resized.forms
import list.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=30)),
                ('desc', models.CharField(max_length=100)),
                ('full_article', models.CharField(max_length=1000)),
                ('datetime', models.DateTimeField()),
                ('image', django_resized.forms.ResizedImageField(blank=True, crop=None, force_format=None, keep_meta=True, null=True, quality=-1, scale=None, size=[1920, 1080], upload_to=list.models.upload_to)),
            ],
        ),
    ]
