# Generated by Django 4.2.11 on 2024-12-12 08:12

from django.db import migrations, models
import list.models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0002_alter_blog_datetime'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='author',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('Tech', 'Tech'), ('Health', 'Health'), ('Lifestyle', 'Lifestyle'), ('Education', 'Education'), ('Business', 'Business'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AddField(
            model_name='blog',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='blog',
            name='keywords',
            field=models.CharField(blank=True, help_text='Comma-separated keywords for SEO', max_length=255),
        ),
        migrations.AddField(
            model_name='blog',
            name='reading_time',
            field=models.IntegerField(blank=True, help_text='Estimated reading time in minutes', null=True),
        ),
        migrations.AddField(
            model_name='blog',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to=list.models.video_upload_to),
        ),
        migrations.AlterField(
            model_name='blog',
            name='desc',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='blog',
            name='full_article',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='blog',
            name='title',
            field=models.CharField(max_length=100),
        ),
    ]
