# Generated by Django 4.2.11 on 2024-12-12 08:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0003_blog_author_blog_category_blog_is_featured_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blog',
            options={'ordering': ['-datetime']},
        ),
    ]
