# Generated by Django 4.2.11 on 2025-06-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('list', '0004_alter_blog_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='category',
            field=models.CharField(choices=[('Tech', 'Tech'), ('Health', 'Health'), ('Lifestyle', 'Lifestyle'), ('Education', 'Education'), ('Business', 'Business'), ('Sports', 'Sports'), ('Opinions', 'Opinions'), ('Startups', 'Startups'), ('Technology', 'Technology'), ('Crime', 'Crime'), ('World', 'World'), ('Art', 'Art'), ('History', 'History'), ('Culture', 'Culture'), ('Finance', 'Finance'), ('Fashion', 'Fashion'), ('Food', 'Food'), ('Travel', 'Travel'), ('Environment', 'Environment'), ('Science', 'Science'), ('Politics', 'Politics'), ('Entertainment', 'Entertainment'), ('Sports', 'Sports'), ('Other', 'Other')], default='Other', max_length=50),
        ),
        migrations.AlterField(
            model_name='blog',
            name='desc',
            field=models.CharField(max_length=2000),
        ),
    ]
